spring:
    application:
        name: ${SERVICE_NAME}
    config:
        import: configserver:${GATEWAY_CONFIG_URL}

info:
  app:
    name: ${SERVICE_NAME}
    description: ${SERVICE_DESCRIPTION}
    version: ${SERVICE_VERSION}
    author: ${AUTHOR_NAME}

logging:
  level:
    '[org.springframework.security]': DEBUG
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.cloud.gateway.server.mvc]': DEBUG