spring:
  application:
    name: ${SERVICE_NAME}

  # datasource:
  #   url: ${DB_URL}
  #   username: postgres
  #   password: root
  #   driver-class-name: org.postgresql.Driver
  
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   database-platform: ${HIBERNATE_DIALECT}

  # data:
  #   redis:
  #     host: ${REDIS_HOST}
  #     port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD:}
    
  config:
    import: configserver:${IDENTITY_CONFIG_URL}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}  

app:
  document:
    application-url: ${DOCUMENT_APPLICATION_URL:https://shaadrag.online/documents}