spring:
  application:
    name: ${SERVICE_NAME}

  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_REPO_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          clone-on-start: false
          force-pull: true

  services:
    creds:
      identity-svc-name: ${IDENTITY_SVC_NAME}
      identity-svc-password: ${IDENTITY_SVC_PASSWORD}
      gateway-svc-name: ${GATEWAY_SVC_NAME}
      gateway-svc-password: ${GATEWAY_SVC_PASSWORD}
server:
  port: ${SERVER_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
                
        include: "*"  # health,info,refresh
  endpoint:
    # shutdown:
    #   access: UNRESTRICTED
    health:
      show-details: always
  
  health:
    defaults:
      enabled: true
    
info:
  app:
    name: ${SERVICE_NAME}
    description: ${SERVICE_DESCRIPTION}
    version: ${SERVICE_VERSION}
    author: ${AUTHOR_NAME}

